"""
Collect the named, value-bearing form fields (radio groups, date inputs, ...)
from a built element tree, and emit them as a small JS manifest.

The manifest is generated from the same :class:`~models.forms.form.Form` tree
used to render ``test.html``, so it can't drift out of sync with the fields
actually present in the page: add a question in ``build_page.py`` and its
field shows up in ``form_variables.js`` the next time the builder runs.
"""

import json
from pathlib import Path

from builder.models.basic.html_tag import HtmlTag
from builder.models.forms.date_input import DateInput
from builder.models.forms.form import Form
from builder.models.forms.integer_input import IntegerInput
from builder.models.forms.radio.radio_group import RadioGroup
from builder.models.forms.text_input import TextInput


def collect_fields(root: HtmlTag) -> list[dict]:
    """Walk an element tree and return a manifest entry per value-bearing field.

    Recurses into anything with an ``elements`` list (``Form``, ``Div`` and its
    subclasses). Each :class:`RadioGroup` contributes one ``radio`` entry
    (read via its ``name``, with its question's ``options`` — the possible
    ``value``s — listed alongside); each :class:`DateInput`/:class:`TextInput`/
    :class:`IntegerInput` contributes one ``date``/``text``/``integer`` entry
    (read via its ``name``). Add another ``isinstance`` branch here when a new
    field-bearing element type is introduced.
    """
    fields: list[dict] = []

    if isinstance(root, RadioGroup):
        fields.append(
            {
                "kind": "radio",
                "name": root.name,
                "options": [option.value for option in root.question.options],
            }
        )
    elif isinstance(root, DateInput):
        fields.append({"kind": "date", "id": root.name})
    elif isinstance(root, TextInput):
        fields.append({"kind": "text", "id": root.name})
    elif isinstance(root, IntegerInput):
        fields.append({"kind": "integer", "id": root.name})

    for child in getattr(root, "elements", []):
        if isinstance(child, HtmlTag):
            fields.extend(collect_fields(child))

    return fields


def write_manifest(form: Form, output_path: Path) -> None:
    """Write ``form_variables.js`` — a field manifest plus a collector function."""
    fields = collect_fields(form)
    fields_json = json.dumps(fields, indent=2)

    js = (
        "// Auto-generated by builder/field_manifest.py — do not edit by hand.\n"
        "// Regenerate by running build_page.py.\n"
        "//\n"
        "// Lists every named, value-bearing field rendered into the form, so\n"
        "// a page's generate-defence JS can read current answers without\n"
        "// hardcoding each field's name/id by hand. Radio fields also list\n"
        "// their `options` (the possible values), so callers can see the\n"
        "// answer set without hardcoding it either.\n"
        "\n"
        f"const FORM_FIELDS = {fields_json};\n"
        "\n"
        "// Reads current answers for each field in FORM_FIELDS from the DOM.\n"
        "// Returns { [name or id]: value }; unanswered radios are null.\n"
        "function collectFormValues() {\n"
        "    const values = {};\n"
        "    FORM_FIELDS.forEach(field => {\n"
        "        if (field.kind === 'radio') {\n"
        "            const checked = document.querySelector(\n"
        "                `input[name=\"${field.name}\"]:checked`\n"
        "            );\n"
        "            values[field.name] = checked ? checked.value : null;\n"
        "        } else {\n"
        "            const el = document.getElementById(field.id);\n"
        "            values[field.id] = el ? el.value.trim() : null;\n"
        "        }\n"
        "    });\n"
        "    return values;\n"
        "}\n"
    )

    output_path.write_text(js, encoding="utf-8")
